/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtividadesRouteImport } from './routes/atividades'
import { Route as ColaboradoresRouteImport } from './routes/colaboradores'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as OcorrenciasRouteImport } from './routes/ocorrencias'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RepositorioRouteImport } from './routes/repositorio'
import { Route as SqlRouteImport } from './routes/sql'
import { Route as UtilizadoresRouteImport } from './routes/utilizadores'
import { Route as VarreduraIaRouteImport } from './routes/varredura-ia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesRoute = AtividadesRouteImport.update({
  id: '/atividades',
  path: '/atividades',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradoresRoute = ColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OcorrenciasRoute = OcorrenciasRouteImport.update({
  id: '/ocorrencias',
  path: '/ocorrencias',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositorioRoute = RepositorioRouteImport.update({
  id: '/repositorio',
  path: '/repositorio',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlRoute = SqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilizadoresRoute = UtilizadoresRouteImport.update({
  id: '/utilizadores',
  path: '/utilizadores',
  getParentRoute: () => rootRouteImport,
} as any)
const VarreduraIaRoute = VarreduraIaRouteImport.update({
  id: '/varredura-ia',
  path: '/varredura-ia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/dashboard': typeof DashboardRoute
  '/ocorrencias': typeof OcorrenciasRoute
  '/perfil': typeof PerfilRoute
  '/repositorio': typeof RepositorioRoute
  '/sql': typeof SqlRoute
  '/utilizadores': typeof UtilizadoresRoute
  '/varredura-ia': typeof VarreduraIaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/dashboard': typeof DashboardRoute
  '/ocorrencias': typeof OcorrenciasRoute
  '/perfil': typeof PerfilRoute
  '/repositorio': typeof RepositorioRoute
  '/sql': typeof SqlRoute
  '/utilizadores': typeof UtilizadoresRoute
  '/varredura-ia': typeof VarreduraIaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atividades': typeof AtividadesRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/dashboard': typeof DashboardRoute
  '/ocorrencias': typeof OcorrenciasRoute
  '/perfil': typeof PerfilRoute
  '/repositorio': typeof RepositorioRoute
  '/sql': typeof SqlRoute
  '/utilizadores': typeof UtilizadoresRoute
  '/varredura-ia': typeof VarreduraIaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atividades'
    | '/colaboradores'
    | '/dashboard'
    | '/ocorrencias'
    | '/perfil'
    | '/repositorio'
    | '/sql'
    | '/utilizadores'
    | '/varredura-ia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atividades'
    | '/colaboradores'
    | '/dashboard'
    | '/ocorrencias'
    | '/perfil'
    | '/repositorio'
    | '/sql'
    | '/utilizadores'
    | '/varredura-ia'
  id:
    | '__root__'
    | '/'
    | '/atividades'
    | '/colaboradores'
    | '/dashboard'
    | '/ocorrencias'
    | '/perfil'
    | '/repositorio'
    | '/sql'
    | '/utilizadores'
    | '/varredura-ia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtividadesRoute: typeof AtividadesRoute
  ColaboradoresRoute: typeof ColaboradoresRoute
  DashboardRoute: typeof DashboardRoute
  OcorrenciasRoute: typeof OcorrenciasRoute
  PerfilRoute: typeof PerfilRoute
  RepositorioRoute: typeof RepositorioRoute
  SqlRoute: typeof SqlRoute
  UtilizadoresRoute: typeof UtilizadoresRoute
  VarreduraIaRoute: typeof VarreduraIaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades': {
      id: '/atividades'
      path: '/atividades'
      fullPath: '/atividades'
      preLoaderRoute: typeof AtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaboradores': {
      id: '/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof ColaboradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocorrencias': {
      id: '/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/ocorrencias'
      preLoaderRoute: typeof OcorrenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositorio': {
      id: '/repositorio'
      path: '/repositorio'
      fullPath: '/repositorio'
      preLoaderRoute: typeof RepositorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilizadores': {
      id: '/utilizadores'
      path: '/utilizadores'
      fullPath: '/utilizadores'
      preLoaderRoute: typeof UtilizadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varredura-ia': {
      id: '/varredura-ia'
      path: '/varredura-ia'
      fullPath: '/varredura-ia'
      preLoaderRoute: typeof VarreduraIaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtividadesRoute: AtividadesRoute,
  ColaboradoresRoute: ColaboradoresRoute,
  DashboardRoute: DashboardRoute,
  OcorrenciasRoute: OcorrenciasRoute,
  PerfilRoute: PerfilRoute,
  RepositorioRoute: RepositorioRoute,
  SqlRoute: SqlRoute,
  UtilizadoresRoute: UtilizadoresRoute,
  VarreduraIaRoute: VarreduraIaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
